name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PGHOST: ${{ secrets.PGHOST }}
      PGPORT: ${{ secrets.PGPORT }}
      PGUSER: postgres
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGDATABASE: ${{ secrets.PGDATABASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for PostgreSQL to start
      run: |
         timeout 5 bash -c '
           until sudo -u postgres psql -c "\\l" &>/dev/null; do
            sleep 1
          done
         '
    - name: Check PostgreSQL status
      run: sudo service postgresql status

      
    - name: Create PostgreSQL user and database
      run: |
        echo "ALTER USER postgres WITH ENCRYPTED PASSWORD '${{ secrets.PGPASSWORD }}';" | sudo -u postgres psql

    - name: Create PostgreSQL database
      run: |
        psql -h localhost -U postgres -d postgres -c "CREATE DATABASE ${{ secrets.PGDATABASE }};"
    - name: List PostgreSQL databases
      run: |
        psql -h localhost -U postgres -l


   
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your desired Python version

    - name: Install pip dependencies
      run: |
        pip install -r requirements.txt

    - name: Run FastAPI application
      run: uvicorn App.main:app --host 0.0.0.0 --port 8000 --reload &

    - name: Wait for FastAPI to start
      run: |
        until curl -s http://localhost:8000/healthz; do
          sleep 1
        done
