name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PGHOST: ${{ secrets.PGHOST }}
      PGPORT: ${{ secrets.PGPORT }}
      PGUSER: postgres
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGDATABASE: ${{ secrets.PGDATABASE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PostgreSQL
      uses: postgres/actions/setup-postgres@v2
      with:
        postgresql-version: '16'
        database: ${{ secrets.PGDATABASE }}
        username: postgres
        password: ${{ secrets.PGPASSWORD }}

    - name: Start PostgreSQL service
      run: sudo service postgresql start

    - name: Wait for PostgreSQL to start
      run: |
        until sudo -u postgres psql -c '\l'; do
          sleep 1
        done
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your desired Python version

    - name: Install pip dependencies
      run: |
        pip install -r requirements.txt

    - name: Run FastAPI application
      run: uvicorn App.main:app --host 0.0.0.0 --port 8000 --reload &

    - name: Wait for FastAPI to start
      run: |
        until curl -s http://localhost:8000/healthz; do
          sleep 1
        done
